{% set name = "lpython" %}
{% set version = "0.22.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/lcompilers/lpython/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 741fb64ddf70528eb713103d5b6e2068344b5768b546b0c21145d5a1507635a0
  patches:
    - version.patch

build:
  number: 0
  skip: true  # [py<36]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ stdlib("c") }}
    - cmake
    - make   # [unix]
    - bison =3.4        # [not win]
    - m2-bison =3.0.4   # [win]
    - xonsh =0.13.4     # [win]
    - ninja             # [win]
    - re2c =2.2

  host:
    - xeus =5.1.0
    - xeus-zmq =3.0.0
    - llvmdev =11.1.0
    - nlohmann_json =3.11.3
    - zlib =1.3.1
  run:
    # xeus breaks abi compatibility in patch versions even though
    # run_exports say otherwise in https://github.com/conda-forge/xeus-feedstock/blob/0896038be810da2944ebcb612e22886815ea691e/recipe/meta.yaml#L18
    - {{ pin_compatible("xeus", max_pin="x.x.x") }}  # [win]
    - zstd =1.5.2  # [x86_64]

test:
  requires:
    - jupyter =1.0.0
  commands:
    - test -f ${PREFIX}/bin/lpython  # [unix]
    - if not exist %LIBRARY_PREFIX%\bin\lpython.exe exit 1  # [win]
    - lpython --help  # [ not osx or not arm64]
    - lpython --version  # [ not osx or not arm64]
    - jupyter kernelspec list --json  # [ not osx or not arm64]
      # This fails if the `fortran` spec is not installed
    - jupyter kernelspec remove -f fortran  # [ not osx or not arm64]

about:
  home: https://lpython.org
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Modern interactive LLVM-based Python compiler
  dev_url: https://github.com/lcompilers/lpython.git

extra:
  recipe-maintainers:
    - certik
